name: Docker Image Builder

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Choose a project?"
        required: true
        type: choice
        options:
          - Frontend
          - Backend
          - All
        default: All
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Frontend
        if: ${{ github.event.inputs.project == 'Frontend' || github.event.inputs.project == 'All' }}
        working-directory: ./Dnd-Interactive-Frontend
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/Dnd-Interactive-Frontend:latest .
      - name: Push Frontend Image
        if: ${{ github.event.inputs.project == 'Frontend' || github.event.inputs.project == 'All' }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/Dnd-Interactive-Frontend:latest


      - name: Build Backend
        if: ${{ github.event.inputs.project == 'Backend' || github.event.inputs.project == 'All' }}
        working-directory: ./Dnd-Interactive-Backend
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/Dnd-Interactive-Backend:latest .
      - name: Push Frontend Image
        if: ${{ github.event.inputs.project == 'Backend' || github.event.inputs.project == 'All' }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/Dnd-Interactive-Backend:latest
