name: Docker Image Builder

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Choose a project?"
        required: true
        type: choice
        options:
          - Frontend
          - Backend
          - All
        default: All
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set lowercase owner
        id: vars
        run: echo "owner_lc=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        
      - name: Build Frontend
        if: ${{ github.event.inputs.project == 'Frontend' || github.event.inputs.project == 'All' }}
        working-directory: ./Dnd-Interactive-Frontend
        run: |
          docker build \
            --build-arg VITE_CLIENT_ID=${{ secrets.VITE_CLIENT_ID }} \
            -t ghcr.io/${{ steps.vars.outputs.owner_lc }}/dnd-frontend:latest .
      - name: Push Frontend Image
        if: ${{ github.event.inputs.project == 'Frontend' || github.event.inputs.project == 'All' }}
        run: |
          docker push ghcr.io/${{ steps.vars.outputs.owner_lc }}/dnd-frontend:latest


      - name: Build Backend
        if: ${{ github.event.inputs.project == 'Backend' || github.event.inputs.project == 'All' }}
        working-directory: ./Dnd-Interactive-Backend
        run: |
          docker build \
            -t ghcr.io/${{ steps.vars.outputs.owner_lc }}/dnd-backend:latest .
      - name: Push Backend Image
        if: ${{ github.event.inputs.project == 'Backend' || github.event.inputs.project == 'All' }}
        run: |
          docker push ghcr.io/${{ steps.vars.outputs.owner_lc }}/dnd-backend:latest
